- id: check-git-user-email
  name: check git user.email
  description: Validate the git user email against allowed domain list.
  entry: check-git-user-email
  language: python
  pass_filenames: false
  always_run: true
- id: check-prohibited-filenames
  name: check prohibited filenames
  description: Checks file names against a list of prohibited names and patterns.
  entry: check-prohibited-filenames
  language: python
  pass_filenames: true
  always_run: false
